repo_project/apps/archivos/urls.py
from django.urls import path
from . import views

app_name = 'archivos'
urlpatterns = [
    path("<str:sigla>/", views.root, name="arch-root"),
    path("ajax/<str:sigla>/", views.zip_ramo, name="zip-ramo"),
    path("", views.pick_ramo, name="pick-ramo"),
    path("upload/", views.archivo_upload, name="archivos-upload")
]

repo_project/apps/ramos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="archivos-home"),
    path("register/", views.register, name="page-login"),

]

repo_project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ramos.urls'), name="archivos"),
    path('archivos/', include('archivos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

repo_project/apps/ramos/models.py
from django.db import models

# Create your models here.


class Ramo(models.Model):
    sigla = models.CharField(max_length=50)
    nombre = models.CharField(max_length=255)
    semestre = models.IntegerField("semestre en que se cursa el ramo")
    def __str__(self):
        return f"{self.sigla}"


class Carrera(models.Model):
    nombre = models.CharField(max_length=255)
    ramos = models.ManyToManyField(Ramo)
    

repo_project/apps/ramos/views/accounts.py
from django.shortcuts import render
from archivos.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

def index(request):
    return render(request,'dappx/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    print("entro aca    ")
    
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.password = make_password(user.password)
            print("save user")
        else:
            print(user_form.errors)
        print(request.POST)
    else:
        user_form = UserForm()
    return render(request,'loginRegister/register.html')

repo_project/apps/ramos/views/home.py
from django.shortcuts import render
from ramos.models import Ramo
# Create your views here.
from django.contrib.auth.decorators import login_required

def home(request):
	all_ramos = Ramo.objects.all()
	ramo_by_semestre = {}
	for ramo in all_ramos:
		semestre = str(ramo.semestre)
		if semestre not in ramo_by_semestre.keys():
			ramo_by_semestre[semestre] = []
		ramo_by_semestre[semestre].append(ramo.sigla)
	ramo_by_semestre = list(ramo_by_semestre.items())
	ramo_by_semestre.sort()
	context = {
		'ramos':all_ramos,
		'ramo_by_semestre':ramo_by_semestre
	}
	print(context)
	return render(request, "home.html", context)

def login(request):
	return render(request, "loginRegister/login.html")

def register(request):
	return render(request, "loginRegister/register.html")

repo_project/templates/ramos/index.html
{% extends 'global/base.html' %} {% block content %}

<a id="download-all" href="">Descargar todo el ramo</a>

<div class="container mt-sm-0 ml-sm-1 mr-sm-1 mt-md-5 ml-md-4 mr-md-4">
  <div class="row">
    <h1 style="color: #fff">{{current}}</h1>
  </div>
  <div class="row">
    <div class="table-responsive">
      <table id="myTable" class="table table-dark table-bordered table-striped">
        <thead>
          <tr>
            <th scope="col-sm-1 col-md-1 col-lg-1 col-xl-1"></th>
            <th scope="col">Nombre</th>
            <th scope="col">Tipo</th>
            <th scope="col">Semestre</th>
            <th scope="col">Fecha</th>
            <th scope="col-sm-2 col-md-2 col-lg-2 col-xl-2">Peso</th>
          </tr>
        </thead>
        <tbody>
          {% for file in files %}
          <tr>
            <td scope="col-sm-1 col-md-1 col-lg-1 col-xl-1">
              <a download href="/media/{{file.archivo}}">
                <center><i class="fa fa-download"></i></center>
              </a>
            </td>
            <td scope="col">{{file.nombre}}</td>
            <td scope="col"><i class="fa fa-file-pdf-o"></i></td>
            <td scope="col">{{file.semestre}}</td>
            <td scope="col">{{file.subido}}</td>
            <td scope="col-sm-2 col-md-2 col-lg-2 col-xl-2">1000 TB</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    $("#myTable").DataTable({
      paging: false,
      stateSave: true,
      info: false,
      language: {
        search: "Filtrar",
      },
    });
  });
  $("#download-all").click(function (e) {
    e.preventDefault();
    var url = "{% url 'archivos:zip-ramo' current %}";
    $.get(url, function (data) {
      window.location.href = "/" + data["link"];
    });
  });
</script>
{% endblock %}