repo_project/apps/archivos/urls.py
from django.urls import path
from . import views

app_name = 'archivos'
urlpatterns = [
    path("<str:sigla>/", views.root, name="arch-root"),
    path("ajax/<str:sigla>/", views.zip_ramo, name="zip-ramo"),
    path("", views.pick_ramo, name="pick-ramo"),
    path("upload/", views.archivo_upload, name="archivos-upload")
]

repo_project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ramos.urls'), name="archivos"),
    path('archivos/', include('archivos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

repo_project/apps/archivos/models.py
from django.db import models
from django.contrib.auth.models import User

from ramos.models import Ramo
# Create your models here.
from django.core.validators import MinValueValidator, MaxValueValidator


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)


def path_of_file(instance, filename):
    return f"{instance.ramo.sigla}/{instance.tipo}/{filename}"


class Archivo(models.Model):
    nombre = models.CharField(max_length=255)
    ramo = models.ForeignKey(Ramo, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=255)
    aceptado = models.BooleanField(default=False)
    semestre = models.CharField(max_length=255, verbose_name='semestre en que se genero el archivo')
    subido = models.DateTimeField(auto_now=False, auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    archivo = models.FileField(upload_to=path_of_file)
    def __str__(self): return self.nombre

repo_project/apps/archivos/forms.py
from django import forms
from .models import Archivo
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password



class ArchivoForm(forms.ModelForm):
    class Meta:
        model = Archivo
        fields = ("nombre", "ramo", "tipo", "semestre", "archivo")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','password','email')

    def save(self, commit=True):
        user = super().save(False)
        user.username = user.email
        user.password = make_password(user.password)
        user = super().save()
        return user


    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        print(f"pass es {password} / confirm pass es {confirm_password}")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

repo_project/apps/archivos/views/archivos_dl_items.py
"""
ENCARGADO DE DESCARGAR TODOS LOS ARCHIVOS ASOCIADOS A UN RAMO, 
DEVUELVE UN JSON {} CON EL ESTADO Y LA UBICACION DEL ZIP
"""
from zipfile import ZipFile
from django.http import JsonResponse
from rest_framework.decorators import api_view

from ..models import Archivo

import random, string
def get_random_str(N=20):
    return ''.join([random.choice(string.ascii_letters) for _ in range(N)])

@api_view(["POST"])
def archivo_dl_selected(request):
    try:
        random_name = get_random_str()+'.zip'
        zip_obj = ZipFile(f'media/media/TEMP/{random_name}', 'w')
        archivos = Archivo.objects.filter(id__in=request.data['files'])
        for file in archivos:
            to_dir = "/".join(str(file.path).split("/")[2:])
            zip_obj.write('media/'+str(file.path), to_dir)
        zip_obj.close()
        return JsonResponse({
            'status':200,
            'url': f"media/media/TEMP/{random_name}"})
    except:
        return JsonResponse({
            'status':400})

repo_project/apps/archivos/views/archivos_download.py
"""
VISTA PARA ARCHIVOS APROBADOS, FORM PARA SELECCIONAR CUALES METER A UN .ZIP
"""
# from django.http import HttpResponse
from zipfile import ZipFile
from random import sample
from django.http import JsonResponse

from django.shortcuts import render
from ..models import Archivo
from ramos.models import Ramo

def root(request, sigla):
    all_files = Archivo.objects.filter(aceptado=True)
    all_ramos = Ramo.objects.all()
    selected_ramo = Ramo.objects.get(sigla=sigla)
    all_files = all_files.filter(ramo=selected_ramo)
    ramo_by_semestre = {}
    for ramo in all_ramos:
        semestre = str(ramo.semestre)
        if semestre not in ramo_by_semestre.keys():
            ramo_by_semestre[semestre] = []
        ramo_by_semestre[semestre].append(ramo.sigla)

    ramo_by_semestre = list(ramo_by_semestre.items())
    ramo_by_semestre.sort()
    context = {
        'files': all_files,
        'ramos': all_ramos,
        'current': sigla,
        'ramo_by_semestre': ramo_by_semestre,
        'zip': None,
    }
    if request.method == 'POST':
        print(u"\u001b[32m")
        filename = ''.join(sample("abcd", 4))
        archivos = all_files.filter(id__in=request.POST.getlist('files'))
        zip_obj = ZipFile(f'media/temp/{filename}.zip', 'w')
        for e in archivos:
            zip_obj.write('media/'+str(e.archivo), str(e.archivo))
        zip_obj.close()
        context['zip'] = '/media/temp/'+filename+".zip"
    # return render(request, 'archivos/listado.html', context)
    return render(request, 'archivos/listado.html', context)


def zip_ramo(request, sigla):
    zip_obj = ZipFile(f'media/zips/{sigla}.zip', 'w')
    all_files = Archivo.objects.filter(aceptado=True)
    selected_ramo = Ramo.objects.get(sigla=sigla)
    all_files = all_files.filter(ramo=selected_ramo)
    for e in all_files:
        zip_obj.write('media/'+str(e.archivo), str(e.archivo))
    zip_obj.close()
    return JsonResponse({'link': f'media/zips/{sigla}.zip'})


def pick_ramo(request):
    all_ramos = Ramo.objects.all()
    context = {
        'ramos': all_ramos
    }
    return render(request, 'archivos/home.html', context)
    

repo_project/apps/archivos/views/archivos_download_ramo.py
"""
ENCARGADO DE DESCARGAR TODOS LOS ARCHIVOS ASOCIADOS A UN RAMO, 
DEVUELVE UN JSON {} CON EL ESTADO Y LA UBICACION DEL ZIP
"""
from zipfile import ZipFile
from django.http import JsonResponse
from rest_framework.decorators import api_view


from ramos.models import Ramo
from ..models import Archivo

@api_view(["GET"])
def archivo_dl_ramo(request, ramo):
    try:
        ramo_inner = Ramo.objects.get(sigla=ramo)
        archivos = Archivo.objects.filter(ramo=ramo_inner)
        zip_obj = ZipFile(f'media/media/TEMP/{ramo}.zip', 'w')
        for file in archivos:
            to_dir = "/".join(str(file.path).split("/")[2:])
            zip_obj.write('media/'+str(file.path), to_dir)
        zip_obj.close()
        return JsonResponse(
            {'status':200,
            'url': f"media/media/TEMP/{ramo}.zip"}
            , safe=False)
    except:
        return JsonResponse(
            {'status':400}
            , safe=False)

repo_project/apps/archivos/views/archivos_upload.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import JsonResponse
from django.core.files.storage import FileSystemStorage
from django.urls import reverse

from ..models import Archivo
from ..forms import ArchivoForm

from ramos.models import Carrera
from ramos.models import Ramo


def archivo_upload(request):
    if request.method == "POST":
        form = ArchivoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect("archivos:archivos-upload")
    else:
        form = ArchivoForm()
        carreras = Carrera.objects.defer()
        ramos = Ramo.objects.all()
    
        
        
        js_carreras = serializers.serialize('json', carreras)
        js_ramos = serializers.serialize('json', ramos)


    return render(request, "archivos/upload.html", {
        "form": form,
        'js_carreras': js_carreras,
        'js_ramos': js_ramos,
        'carreras': carreras,
        'ramos': ramos

    })

repo_project/templates/archivos/aux_upload.html
<h2>Upload</h2>
{{ form.non_field_errors }}
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}

    <button type="submit">Upload File</button>
</form>

repo_project/templates/archivos/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sci-hub-usm</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block title %}{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"
    />
    {% block style %} {% endblock style %}
  </head>

  <body>
    {% block content %} {% endblock content %}

    <script
      src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/v/ju/dt-1.10.22/r-2.2.6/sl-1.3.1/datatables.min.js"
    ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %} {% endblock javascript %}
  </body>
</html>

repo_project/templates/archivos/index.html
HOLA MUNDO

repo_project/templates/archivos/listado.html
{% extends 'global/base.html' %} {% block content %}

<div class="container pl-5 mt-sm-0 mr-sm-1 mt-md-3 mr-md-4">
  <div class="row">
    <h1 style="color: #fff">{{current}}</h1>
  </div>
  <div class="row">
    <a id="download-all" href="">Descargar todo el ramo</a>
  </div>
  

  <form action="{% url 'archivos:arch-root' current %}" method="post">
    <div class="row">
      {%csrf_token%}
      <!-- <table id="myTable"> -->
      <table
        id="filetable"
        class="table table-dark table-bordered table-striped"
      >
        <thead>
          <tr>
            <th></th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Sem</th>
            <th>Fecha</th>
            <th>Link</th>
          </tr>
        </thead>
        <tbody>
          {% for file in files %}
          <tr>
            <td>
              <center>
                <input
                  type="checkbox"
                  id="{{file.id}}"
                  name="files"
                  value="{{file.id}}"
                />
              </center>
            </td>
            <td>{{file.nombre}}</td>
            <td>{% if file.tipo == 'PDF' %} 
                  <i class="fa fa-file-pdf-o"></i> 
                {% elif file.tipo == 'WORD'%}
                  <i class="fa fa-file-word-o"></i> 
                {% elif file.tipo == 'PPT'%}
                  <i class="fa fa-file-powerpoint-o"></i> 
                {% endif %}</td>
            <td>{{file.semestre}}</td>
            <td>{{file.subido}}</td>
            <td>
              <a download href="/media/{{file.archivo}}"><i class="fa fa-download"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="row">
      <input type="submit" value="Crear .zip" />
    </div>
  </form>

  <a href="{{zip}}">{{zip}}</a>
</div>

{% endblock %}

repo_project/templates/archivos/pick.html
{% extends 'archivos/base.html' %} {% block content %}
<h1>Pick your Poison</h1>
<div>
  {% for ramo in ramos %}
  <div>
    <a href="/archivos/{{ramo.sigla}}">{{ramo.sigla}} - {{ramo.nombre}}</a>
  </div>
  {% endfor %}
</div>

{% endblock %}

repo_project/templates/archivos/upload.html
{% extends 'global/base.html' %}
{% load static %}
{% block head %}

<script type="text/javascript">
  {% autoescape off %}
    let carreras = {{js_carreras}}
    let ramos = {{js_ramos}}
  {% endautoescape %}

</script>
<script defer type="text/javascript" src="{% static 'archivos/upload.js' %}"></script>

{% endblock %}

{% block content %}
<div class="row text-white">
  <div class="col mb-3">
    <h1 class="display-4">Titulo generico</h1>
  </div>
</div>
<form action="/archivos/upload/" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="row text-white mb-3 mt-4">
    <div class="col-12">
      <h5>Seleccion del ramo</h5>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <select id="select-carrera" class="custom-select" >
        <option  selected>Selecciona la carrera</option>
        {% for carrera in carreras %}
          <option value="{{carrera.id}}">{{carrera.nombre}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <select id="select-semestre" class="custom-select" disabled>
        <option disabled selected>Semestre</option>
      </select>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <select id="select-ramo" class="custom-select" name="ramo" disabled>
        <option disabled selected>Selecciona el ramo</option>
      </select>
    </div>
    
  </div>
  <div class="row text-white mb-3 mt-1">
    <div class="col-12">
      <h5>Informacion del archivo</h5>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <select class="custom-select" name="tipo">
        <option disabled selected >Tipo de archivo</option>
        <option value="Certamen">Certamen</option>
        <option value="Tarea">Tarea</option>
        <option value="Otro">Otra cosa</option>
      </select>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <input type="text" name="semestre" class="form-control" id="validationDefault02" placeholder="2012-2" required >
      <small id="passwordHelpBlock" class="form-text text-muted">
        Año en que aparecio
      </small>
    </div>
    <div class="col-12 col-sm-4 mb-3">
      <input type="text" class="form-control" name="nombre" id="validationDefault02" placeholder="1" required>
      <small id="passwordHelpBlock" class="form-text text-muted">
        Nombre
      </small>
    </div>
  </div>
  <div class="row text-white mb-3 mt-1 justify-content-center">
    <div class="col-6 text-center">
      <h5>Sube tu archivo</h5>
    </div>
    </div>
  <div class="row text-white mb-3 mt-1 justify-content-center">
    <div class="col-12 col-sm-6">
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="archivo" required>
        <label class="custom-file-label">Escoger archivo</label>
      </div>
    </div>
  </div>
  <div class="row text-white mb-3 mt-5 justify-content-center">
    <div class="col-12 col-sm-6">
      <button class="btn btn-success btn-block btn-lg">Subir!</button>
    </div>
  </div>
</form>


{% endblock %}